### ISSUE TITLE
Implement export feature

### ISSUE THREAD

**Issue by sryazanov** [ili-toolbox/ili#1]
Design doc: https://docs.google.com/document/d/10AJ-x3GakM8ExQ8ZDfHPhYAxD2zStQjbpdNtOJv4jxg/edit?usp=sharing

**Comment by theodev** [comment]
plz see my comments in the file

**Comment by theodev** [comment]
set up pixel ratio to be used when storing PNG
examples: 0.5, 1 (default), 2, 4
(2 = the X and Y are twice larger than the screen resolution if the browser is full-screen)

**Comment by theodev** [comment]
works like a charm :)
