### ISSUE TITLE
Zoom in 2D is too fast on Mac when using MacBook Pro touchpad/magic mouse

### ISSUE THREAD

**Issue by theodev** [ili-toolbox/ili#10]
Can you please slow it down by at least 2 times (if it doesn't make it unreasonably slow on Win/Lin)?

**Comment by theodev** [comment]
set in View2D.SCALE_CHANGE
should be larger than 1

**Comment by sryazanov** [comment]
I've changed the factor from 1.2 to 1.1. @theodev please check it with Mac trackpad.

**Comment by theodev** [comment]
good now!
