### ISSUE TITLE
2d data load fails 

### ISSUE THREAD

**Issue by andy-d-palmer** [ili-toolbox/ili#15]
files: lung.csv/lung.png from demo 
system: OSX 10, chrome Version 42.0.2311.135 (64-bit)

to reproduce: drag-drop pair of files into browser 
result: data fails to load, see screenshot for log
![screen shot 2015-05-04 at 14 00 48](https://cloud.githubusercontent.com/assets/10552145/7453103/0e05d1fe-f266-11e4-8a40-ed2fe54e856a.png)

**Comment by andy-d-palmer** [comment]
error only appears after clicking within the window - data-load completes without an error in the log

**Comment by sryazanov** [comment]
Hi Andy, sorry, mirror on the github.io was quite old. I've just updated it. Could you please try again?

**Comment by andy-d-palmer** [comment]
Hi Sergey, it's still not working - still returns a blank screen with no m/z values loaded. The uncaught error doesn't seem to occur any more though. Same behaviour with drag-drop and file menu.

**Comment by andy-d-palmer** [comment]
issue was data integrity
