### ISSUE TITLE
сhanging log-lin scale does not update dat.gui

### ISSUE THREAD

**Issue by theodev** [ili-toolbox/ili#26]
see details https://github.com/ili-toolbox/ili/commit/bf2e3675a28c15fad2461c10139772cd1ef9ef8b

**Comment by theodev** [comment]
dat.gui should show min/max in log scale (the same as in the legend) when switching to log-scale

**Comment by sryazanov** [comment]
It was a design decision actually. I thought that ability to see the raw intensities was important.

**Comment by theodev** [comment]
thanks
