### ISSUE TITLE
[bug - minor] link in spot text should open in new window

### ISSUE THREAD

**Issue by andy-d-palmer** [ili-toolbox/ili#27]
currently it replaces the current window so the whole map has to be reloaded. 

minor as immediate workaround is to right click and 'open in new tab/window'

**Comment by theodev** [comment]
This is how it works now, either right click or Ctrl-click (Win), Cmd-click (Mac).

Doesn't it work for you?

**Comment by theodev** [comment]
ah, got it, you don't like exactly this behavior. 

we decided on it because this is how http links work in a browser. 

however, I agree, having a warning before leaving `ili would be good.

**Comment by theodev** [comment]
I'll close this issue and open a new one (not prescribing how it should be but rather documenting the problem)

**Comment by andy-d-palmer** [comment]
It’s pretty usual for links to open a new tab/window. I would say it’s even expected in the case where replacing the current window could require a lot of processing to be redone. It’s not a huge issue and I guess _most_ people will know to ctrl/cmd-click
