### ISSUE TITLE
Global shortcuts for map selection

### ISSUE THREAD

**Issue by sryazanov** [ili-toolbox/ili#3]
Currently the user needs to open MapSelector to change map. Since it's expected to be important operation we want to let changing a map from any context.

In addition to up/down/page-up/page-down key strokes to handle Ctrl+\* strokes. Ctrl variant differ in the following way: it works in global context (whatever focus in, except opened combobox - platform limitation) and and if MapSelector isn't active it shows it shortly with 0.1 opacity (to give the user sense of conntext).

Ctrl+page up/down is intercepted by browser and won't work in a web page.

Some explanation regarding showing the MapSelector. Result of up/down depends on current filter. If we ignore the filter on Ctrl-... it would be confusing. If we apply the filter now showing it's applied it also may be confusing.
If we handle up/down globally (without Ctrl) we may interfere with dat.gui and cause the same sort of confusing that OrbitController caused with lighting. Ctrl gives some sort of uniformity - it's how we handle context independent shortcuts.

**Comment by sryazanov** [comment]
Fixed

**Comment by theodev** [comment]
Hm, there is a problem on Mac that Ctrl-arrows are taken (Ctrl- not Cmd-), Ctrl-left / Ctrl-right for switching between desktops, Ctrl-up / Ctrl-down for showing windows on the desktop / of the same application. 

Maybe to use Alt- instead? (Alt- on Mac is a "within-window" function e.g. in the text it jumps from one word to another, not changing.)
