### ISSUE TITLE
webpage freezes when using Ctrl-s for a large dataset

### ISSUE THREAD

**Issue by theodev** [ili-toolbox/ili#35]
dataset (15K spots) in the db, example_2D_Jeramie/bugreport. Ctrl-s of any map eats 1GB memory, second Ctrl-s (either the same or another map) eats 7GB memory, third Ctrl-s normally has not enough memory and freezes the webpage. 

using a smaller PNG (e.g. 50% x, 50% y) doesn't help

**Comment by sryazanov** [comment]
I tried to investigate the memory leak and have not yet succeeded (so don't expect this to be fixed soon). Apparently 3D mode is not vulnerable.

May be I should mitigate SVG in exporting code. But if SVG leaks memory it also could affect reloading intensities/background image.

Also would be cool to:
1. Indicate that export is in progress and
2. Prevent user from launching many export operations in parallel (once it could exhaust memory).

**Comment by sryazanov** [comment]
I've tried canvas-based rendering and found it much much faster. I thinks we should get rid of most SVG stuff eventually for better performance.
