### ISSUE TITLE
support for tsv data files

### ISSUE THREAD

**Issue by cuttlefishh** [ili-toolbox/ili#38]
csv is fine for most purposes, but some of my category labels have commas, which I have to change to periods or something else. Support for tsv files would be a convenient solution.

**Comment by sryazanov** [comment]
Don't CSV quoted fields (http://edoceo.com/utilitas/csv-file-format) work for you?

**Comment by cuttlefishh** [comment]
Yes, that does work! I see that Excel does this automatically when saving as CSV (I was not using Excel before).
