### ISSUE TITLE
scale bar values low and show 3 decimal places even for integer values

### ISSUE THREAD

**Issue by cuttlefishh** [ili-toolbox/ili#59]
In my data tables, the max value in the scale bar is ~20% less than in the respective column in the data table. I can't get it to display correctly.

Also, even for integer values in my data table, the legend displaces 3 decimal places. Is there a way to just show integer values when the column is integers?

**Comment by iprotsyuk** [comment]
Thanks for reporting. Could you please share your data somehow so that we are able to reproduce the problem.

Regarding your second point: currently, it's not possible to change the default format for numbers. Probably, we'll fix this in future.

**Comment by cuttlefishh** [comment]
Sure!  Here you go...

**Comment by cuttlefishh** [comment]
The issue was the "Hotspot quantile", i.e. hotspot removal using quantile thresholding, which lowers the max value displayed on the colormap, and renders any values above that threshold with the "darkest" color. The default value for hotspot quantile is 0.95. From my perspective it would be more user-friendly if the default were 1, since lowering the threshold is perhaps a more advanced use case. Is that something you'd consider changing? However, I know some of the MS users might prefer have the threshold less than 1 by default. If that's the main use case, I'm OK with that too.

**Comment by theodev** [comment]
Hey Luke,

Thanks for suggestion! Makes sense, will do.

T
