### ISSUE TITLE
Default zoom

### ISSUE THREAD

**Issue by sryazanov** [ili-toolbox/ili#6]
When new image or mesh loaded appropriate view should take appropriate zoom factor for current layout and image/mesh size.

**Comment by sryazanov** [comment]
Proposal: default zoom on doubleclick.
Proposal: loosless zoom on Ctrl+doubleclick. Loose less zoom - match image pixel to screen pixel (devicePixelRatio).

**Comment by theodev** [comment]
This would be a nice feature but not high priority

If to go for it, then either way is fine (double-click or Ctrl-doubleclick) 

Can you please start adding the shortcuts into a separate file? Thanks!

**Comment by theodev** [comment]
POSTPONED
