### ISSUE TITLE
loading datasets through http (by providing URL)

### ISSUE THREAD

**Issue by theodev** [ili-toolbox/ili#8]
specifying http://...csv and http://...stl as arguments to the toolbox URL
STEP1: on the same server (inside the ili folder)
STEP2: on the external website

**Comment by sryazanov** [comment]
Do we really need external downloading? this project is opensourced, therefore everyone could clone it and add own files to the demo folder.

**Comment by theodev** [comment]
for many people who I know will be using the toolbox git-cloning is beyond their current knowledge 

if you feel it's too complicated and you are about to skip it, shall we discuss it tmrw? it's pretty important feature and I would like to discuss before we abandon it

**Comment by sryazanov** [comment]
It's just a suggestion, let's discuss it. Just make sure that security aspect of downloading arbitrary file from Internet has carefully canalized.
