### ISSUE TITLE
Move legend position in online version

### ISSUE THREAD

**Issue by adamsorbie** [ili-toolbox/ili#91]
Hi, 

Great tool by the way, ili has been very useful for my current project. However, I have one problem, I can't seem to export an image without the legend overlaid onto my image. I couldn't see any option to change the position of the legend. Am I missing something or is this not possible at the moment?

**Comment by theodev** [comment]
Hi @adamsorbie, thanks for the feedback! It's not possible to export without legend neither to change the position of the legend indeed. You can use a trick by zooming out a bit s.t. the legend is not overlaid with your image, and then crop it off later after the export.

**Comment by adamsorbie** [comment]
Ok thanks! Strangely, I had the opposite experience. When zooming out the legend was placed directly over the middle of my image but when zooming in it was placed at the bottom, covering only the very bottom part of my figure. The image i'm using has kind of unusual dimensions (315 x 2115) could that potentially cause problems?

**Comment by theodev** [comment]
I think this is alright. Another trick -- you can resize your browser window to adjust it so that the legend doesn't overlap with your image.

**Comment by adamsorbie** [comment]
I'll give that a try, thanks a lot for your help!
